# Parameter search space 
params:
  zone_1_type:         {type: int, low: 1, high: 4} # example discrete switch
  zone_1_Rin:          {type: float,  low: 1,  high: 20.0}
  zone_1_Rout:         {type: float,  low: 200.0, high: 300.0}
  zone_1_Rc:           {type: float,  low: 5.0, high: 50.0}
  zone_1_edge:         {type: float,  low: 0, high: 5}
  zone_1_dust_mass:    {type: float, low: 1e-5, high: 1, scale: log}
  alpha_viscosity:      {type: float, low: 1e-6, high: 1e-1, scale: log}
  zone_1_species_1_optical_indices_file:  {type: categorical, choices: [astro_sil, mix_sil_car, dshark]} #example of categorical switch
  
constraints:
  - "zone_1_Rin < zone_1_Rout"
  - "zone_1_Rc>zone_1_Rin"

#just a sample for the fidelity
fidelity_defaults:
  F0: {photons: 2.0e5, wavelengths: sed_only} #just SED
  F1: {photons: 4.0e5, wavelengths: {vis_mono: [Hc,Kc,Lc,Nc]}} #SED + monochromatic interferometry
  F2: {photons: 6.0e5, wavelengths: {vis_mono: [Hc,Kc,Lc,Nc], pol: [Hc]}, image_ds: 2} # above + radial polarimetric curve
  F3: {photons: 1.0e6, wavelengths: {vis_chromatic: {H:8,K:8,L:6,N:6}, pol: [I,H]}, image_ds: 1} # above + chromatic interferometric V2, polarimetric colour

likelihood_floors:
  sigma_mod_sed: 0.05     # 5% of SED σ (applied inside)
  sigma_mod_v2:  0.03     # absolute floor on V^2
  sigma_mod_pol: 0.07     # fraction of local PI RMS

fixed:
  distance_pc: 1220